### PR TITLE
Iris: Added iris model with 3d gimbal and yaw joint control

### PR DESCRIPTION
**Pull request by snktshrma**
Added gimbal_small_3d model to Iris and added yaw control channel as 6 to AP plugin. Used the same world as gimbal.sdf world.
I'll make changes to the world or existing models as the maintainers say.

### CODE REVIEW

**Comment by srmainwaring** [comment]
Hi @snktshrma, thanks for the PR. Rather than add a new model and world we could do the following with the Iris:

1. Change the 2D gimbal in the `iris_with_gimbal` model for the 3D version with the zoom, and add the extra joint controller and control block.
2. Use the `iris_with_gimbal` in the `iris_runway.sdf` and `iris_warehouse.sdf` worlds.

This keeps the number of models and worlds to maintain in this repo down, and makes the camera equipped model the default. The default params (`gazebo-iris`) in the ardupilot repo would not be configured to control the camera, but we could provide an additional set, and in the meanwhile the camera and gimbal could still be controlled using the `gz` topics.

Thoughts?

**Comment by snktshrma** [comment]
Hey @srmainwaring ! That seems fine! I have made the required changes and will push them asap!

**Comment by snktshrma** [comment]
@srmainwaring I have made the changes you mentioned. Regarding gz control, that seems feasible for the time being I'd say.

**Comment by srmainwaring** [comment]
Closed in favour of #102

**Pull request closed without merging**
