### PR TITLE
Using `setup-gazebo` GitHub Action to install Gazebo in CI

### LINKED ISSUE #126: Proposal to use `setup-gazebo` GitHub Action in CI
## Feature request

**Is your feature request related to a problem? Please describe.**
The current CI performs many manual tasks such as installing Gazebo and all its dependencies, including managing the repository keys. 

**Describe the solution you'd like**
Following [official Gazebo documentation](https://gazebosim.org/docs/latest/setup_gazebo_in_ci/), it recommends using the [`setup-gazebo`](https://github.com/gazebo-tooling/setup-gazebo) GitHub Action to help create a Gazebo environment in CI. 

The action works on three platforms - Ubuntu, macOS and Windows and can be run using a matrix to spawn multiple parallel jobs.

**Additional context**
More usage documentation can be found on the [GitHub Marketplace page](https://github.com/marketplace/actions/setup-gazebo-environment).

### PR DESCRIPTION
**Pull request by sauk2**
Closes #126 

## Summary

This PR changes the CI to use the `setup-gazebo` GitHub Action to configure a Gazebo environment. It replaces Harmonic's installation steps and passes input to the action to take care of the installation.

### CODE REVIEW

**Comment by srmainwaring** [comment]
@sauk2 thanks for the PR. Can you please squash and rebase your changes on `main`. The workflow favoured by ArduPilot does not use merge commits (https://ardupilot.org/dev/docs/git-rebase.html).

**Comment by sauk2** [comment]
> @sauk2 thanks for the PR. Can you please squash and rebase your changes on `main`. The workflow favoured by ArduPilot does not use merge commits (https://ardupilot.org/dev/docs/git-rebase.html).

Sure, thanks for pointing it out! I have squashed all commits into one

**Review by srmainwaring — APPROVED** [review]
Thanks, this is definitely an improvement and we should be able to apply the same change to some of out other repos that depend on Gazebo and `ros_gz`.

**Review by Ryanf55 — APPROVED** [review]
This is an excellent improvement. I checked through the [action.yml](https://github.com/gazebo-tooling/setup-gazebo/blob/main/action.yml) file to see if there were any other options we could to set to speed up the CI, and didn't see any.

**Comment by Ryanf55** [comment]
Yep, we use matrix on some other repos to maintain multiple ROS distros.

Are you interested in doing any more gazebo+CI+ROS related tasks for ArduPilot's Gazebo usage? We have a few you might be able to knock out that would be of great benefit to this project.
* Fixing rosdep errors by using Gazebo's rosdep keys list
* Adding some basic smoke tests of our examples that run in CI (arm, takeoff,  send waypoint command, check the vehicle reaches a location)
* Adding support in CI for ROS 2 Jazzy

**Comment by sauk2** [comment]
> Are you interested in doing any more gazebo+CI+ROS related tasks for ArduPilot's Gazebo usage? We have a few you might be able to knock out that would be of great benefit to this project.
> 
> * Fixing rosdep errors by using Gazebo's rosdep keys list
> * Adding some basic smoke tests of our examples that run in CI (arm, takeoff,  send waypoint command, check the vehicle reaches a location)
> * Adding support in CI for ROS 2 Jazzy

Sorry, I missed this comment. I would be happy to contribute more! Could I ask you to raise issues so we can discuss this more?

**Pull request merged**
