### PR TITLE
Change license from GPLv3+ to LGPLv3+

### PR DESCRIPTION
**Pull request by khancyr**
This change of license intend to allow broader usage of our gazebo plugin by including it into larger gazebo changes.

I am not even sure we could have use the GPLv3 license in first place.

The change is not retroactive, so the anything before this commit can still be used as GPLv3 code, and forked as such.
This change will also apply to Gazebo-classic plugin for the few that still use it. 

I will try to contact every contributors.
The full list is bellow, it it be updated with the answers from the devs.

Just ack with an OK or something visible ! thanks

- [x] @srmainwaring 
- [x] @khancyr 
- [x] @Ryanf55 
- [x] @acxz  
- [x] @41Mo 
- [x] @SwiftGust 
- [x] @clydemcqueen 
- [x] @ahcorde 
- [x] @Rezenders 
- [x] @tridge 
- [x] @kant

### CODE REVIEW

**Review by Ryanf55 — APPROVED** [review]

**Review by acxz — APPROVED** [review]
> I am not even sure we could have use the GPLv3 license in first place.

I'm totally okay with this change, if it means we are following the legal precaution to better integrate ardupilot and gazebo.

**Comment by 41Mo** [comment]
I'm totally ok with this change

**Comment by srmainwaring** [comment]
@khancyr - I support. The license comments in the source code need to be updated to LGPLv3.

We'll need to check the status of these files taken from the core ArduPilot codebase:
- Socket.cpp
- Socket.h

This file has the wrong notice in it (the header is ok):
- ParachutePlugin.cc

These files are Apache License, Version 2.0, although ArduPilot should also be in the copyright as there is only a small amount of residual code from the original versions now.
- ArduPilotPlugin.hh
- ArduPilotPlugin.cc

The ArduCopterIRLockPlugin has not been ported to Gazebo Garden/Harmonic - we could just remove it? It's been kept as a reference in case someone wanted the feature, but no one has asked (someone will now though - for sure).

The `package.xml` file used by the colcon build has a license field.

**Comment by ahcorde** [comment]
I'm totally ok with this change

**Comment by clydemcqueen** [comment]
I support, thanks

**Comment by khancyr** [comment]
@srmainwaring thanks for pointing this.

I have remove the IRLock plugin. We got other way to do this in SITL now so we can deprecate this.
For parachute : from history, it looks like it was taken from px4 repo, so it should be Apache 2, shouldn't it ?

We need to check the issue with Socket.h/cpp as they are taken from ardupilot ... so theorically they inherit from the GPL and will mess up with everything.

**Comment by khancyr** [comment]
> tridge peterbarker staroselskii muramura lucasdemarchi 

SocketAPM only have a few contributors, so we could ask them too to relicense our fork. Before spamming everybody with this,  I have ask first Tridge on about this as he is the main author.

**Comment by kant** [comment]
I'm totally ok with this change

**Comment by tridge** [comment]
@khancyr I'm happy with the change

**Comment by Rezenders** [comment]
I am also happy with the changes

**Comment by Ryanf55** [comment]
Awesome, everyone responded. Assuming we can get CI to pass, let's merge this in soon:)

**Comment by srmainwaring** [comment]
> Awesome, everyone responded. Assuming we can get CI to pass, let's merge this in soon:)

Not quite so fast: `Socket.h` and `Socket.cpp` need to be replaced/rewritten as they are from `ardupilot/libraries/AP_HAL/utility` and licensed GPL.

**Comment by Ryanf55** [comment]
I can help do that. Perhaps we can use it to switch to asio.

**Comment by khancyr** [comment]
@Ryanf55 @srmainwaring socketAPM is dead. We should be good now !

**Comment by srmainwaring** [comment]
> @Ryanf55 @srmainwaring socketAPM is dead. We should be good now !

@khancyr thanks for the changes. There is a lot going on in this PR. Can the code changes be split into a number of PRs, separate from the licence change as some of these are style changes and others such as the warning levels will need to be checked on various platforms.

In addition to the license change we have:

- Replacing SocketAPM with SocketUDP
- Changing warning levels and target includes in CMakeLists.
- Removing old / deprecated plugins
- Changes to class style (final keywords, function signatures etc)
- Not using this-> for member access (which is a change from the Gazebo convention)
- Changing member variable names to m_name etc. (also a change from Gazebo convention).

**Comment by khancyr** [comment]
yes I can move the non licenses related change to another PR

**Comment by khancyr** [comment]
@srmainwaring updated with only the changes need for the license update 

- Replacing SocketAPM with SocketUDP to not carry gpl from it.
- remove IRLOCK plugin to not have to look at licensing issues on it
- add proper license everywhere

**Pull request merged**
